/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const V1TagsGetHandler = http.get('/v1/tags',() => {
  return new HttpResponse.json({
    tags:[
    {
    id:'5fca13d6-1ba2-47cc-a53f-42e9d7acae9b',
    name:'Bertram Armstrong',
    color:'#CE272F',
    },
    {
    id:'38f4c32e-1faa-42d1-bfca-273e9265a51d',
    name:'Bertram Armstrong',
    color:'#CE272F',
    },
    {
    id:'afa80f26-1a77-456f-aec8-6a2b94f173e8',
    name:'Bertram Armstrong',
    color:'#CE272F',
    },
    {
    id:'55640064-c68e-4eee-a403-8d33aba2ca8e',
    name:'Bertram Armstrong',
    color:'#CE272F',
    },
    ],
  })
})
export const tagsServiceHandlers = [
  V1TagsGetHandler,
]
