/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const V1TagsGetHandler = http.get('/v1/tags',() => {
  return HttpResponse.json({
    tags:[
    {
    id:'14c970f6-f6d7-4889-9356-04ff30f42703',
    name:'Elmo Sauer Jr.',
    color:'#B71800',
    },
    {
    id:'06b46e9f-5fb8-461f-a116-89af32f8d8e3',
    name:'Elmo Sauer Jr.',
    color:'#B71800',
    },
    {
    id:'6d1ca9f8-7189-48df-8920-496152210884',
    name:'Elmo Sauer Jr.',
    color:'#B71800',
    },
    {
    id:'a08b7b54-0ee3-4cfc-9650-fb4c7aeb9383',
    name:'Elmo Sauer Jr.',
    color:'#B71800',
    },
    {
    id:'4330442d-7b9a-4dcd-95e4-6a047e22b37d',
    name:'Elmo Sauer Jr.',
    color:'#B71800',
    },
    ],
  })
})
export const tagsServiceHandlers = [
  V1TagsGetHandler,
]
