/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const V1TagsGetHandler = http.get('/v1/tags',() => {
  return HttpResponse.json({
    tags:[
    {
    id:'debc5657-bcd3-41fa-a059-7d0fb7f39335',
    name:'Mr. Braeden Sipes',
    color:'#013008',
    },
    {
    id:'0897c1b8-f581-475d-ae9a-99659b4c7951',
    name:'Mr. Braeden Sipes',
    color:'#013008',
    },
    {
    id:'cf018a39-b305-4f41-a7d7-f16738118b31',
    name:'Mr. Braeden Sipes',
    color:'#013008',
    },
    ],
  })
})
export const tagsServiceHandlers = [
  V1TagsGetHandler,
]
